name: QqGroupManager
version: '${project.version}'
main: cn.paper_card.qqgroupmanager.QqGroupManager
api-version: 1.19

depend:
  - PaperCardAuth

commands:
  get-member-info:
    permission: qq-group-manager.get-member-info

permissions:
  qq-group-manager.get-member-info:
    default: op
